language: php
php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 5.6

services:
  - mysql

dist: trusty
sudo: required

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - bash initial.sh > /dev/null

script:
  - php vendor/bin/codecept run functional
