<?php
namespace MessageBundle\Controller;

use Sonata\AdminBundle\Controller\CRUDController;

class MessageUserController extends CRUDController
{
    public function createAction()
    {
        return parent::createAction(); // TODO: Change the autogenerated stub
    }
}