<?php
namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Get all users by group_id
     * @param $id
     *
     * @return array
     */
    public function findByGroupId($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->leftJoin('u.groups', 'g')
            ->where('g.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
